/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSLibrary.RPC.XDR;

namespace NFSLibrary.Protocols.V3.RPC.Mount
{
    public class MountBody : XdrAble
    {
        private Name _hostname;
        private Name _directory;
        private MountList _nextentry;

        public MountBody()
        { }

        public MountBody(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._hostname.XdrEncode(xdr);
            this._directory.XdrEncode(xdr);
            this._nextentry.XdrEncode(xdr);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._hostname = new Name(xdr);
            this._directory = new Name(xdr);
            this._nextentry = new MountList(xdr);
        }

        public Name HostName
        {
            get
            { return this._hostname; }
        }

        public Name Directory
        {
            get
            { return this._directory; }
        }

        public MountList NextEntry
        {
            get
            { return this._nextentry; }
        }
    }
    // End of mountbody3.cs
}