/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.RPC.XDR;

namespace NFSLibrary.Protocols.V3.RPC.Mount
{
    public class MountList : XdrAble
    {
        private MountBody _value;

        public MountList()
        { }

        public MountList(MountBody value)
        { this._value = value; }

        public MountList(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            if (this._value != null)
            {
                xdr.XdrEncodeBoolean(true);
                this._value.XdrEncode(xdr);
            }
            else { xdr.XdrEncodeBoolean(false); };
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._value = xdr.XdrDecodeBoolean() ? new MountBody(xdr) : null;
        }

        public MountBody Value
        {
            get
            { return this._value; }
        }
    }
    // End of mountlist3.cs
}