/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSClient.RPC.XDR;

namespace NFSLibrary.Protocols.Commons
{
    public class Exports : IXdrData
    {
        private ExportNode _value;

        public Exports()
        { }

        public Exports(ExportNode value)
        { this._value = value; }

        public Exports(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            if (this._value != null)
            {
                xdr.XdrEncodeBoolean(true);
                this._value.XdrEncode(xdr);
            }
            else { xdr.XdrEncodeBoolean(false); };
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._value = xdr.XdrDecodeBoolean() ? new ExportNode(xdr) : null;
        }

        public ExportNode Value
        {
            get
            { return this._value; }
        }
    }

    public class ExportNode : IXdrData
    {
        private Name _mountpath;
        private Groups _exgroups;
        private Exports _next;

        public ExportNode()
        { }

        public ExportNode(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._mountpath.XdrEncode(xdr);
            this._exgroups.XdrEncode(xdr);
            this._next.XdrEncode(xdr);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._mountpath = new Name(xdr);
            this._exgroups = new Groups(xdr);
            this._next = new Exports(xdr);
        }

        public Name MountPath
        {
            get
            { return this._mountpath; }
        }

        public Groups ExportGroups
        {
            get
            { return this._exgroups; }
        }

        public Exports Next
        {
            get
            { return this._next; }
        }
    }
    // End of exports.cs
}