/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSLibrary.RPC.XDR;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class AccessAccessOK : IXdrData
    {
        private PostOperationAttributes _obj_attributes;
        private int _access;

        public AccessAccessOK()
        { }

        public AccessAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._obj_attributes.XdrEncode(xdr);
            xdr.XdrEncodeInt(this._access);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._obj_attributes = new PostOperationAttributes(xdr);
            this._access = xdr.XdrDecodeInt();
        }

        public PostOperationAttributes Attributes
        {
            get
            { return this._obj_attributes; }
        }
    }

    public class AccessAccessFAIL : IXdrData
    {
        private PostOperationAttributes _obj_attributes;

        public AccessAccessFAIL()
        { }

        public AccessAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        { this._obj_attributes.XdrEncode(xdr); }

        public void XdrDecode(XdrDecodingStream xdr)
        { this._obj_attributes = new PostOperationAttributes(xdr); }

        public PostOperationAttributes Attributes
        {
            get
            { return this._obj_attributes; }
        }
    }
    // End of ACCESS3res.cs
}