/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSClient.RPC.XDR;

namespace NFSClient.Protocols.V3.RPC
{
    public class CommitArguments : IXdrData
    {
        private NFSHandle _file;
        private long _offset;
        private int _count;

        public CommitArguments()
        { }

        public CommitArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            _file.XdrEncode(xdr);
            xdr.XdrEncodeLong(_offset);
            xdr.XdrEncodeInt(_count);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            _file = new NFSHandle();
            _file.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            _file.XdrDecode(xdr);
            _offset = xdr.XdrDecodeLong();
            _count = xdr.XdrDecodeInt();
        }

        public NFSHandle File
        {
            get { return _file; }
            set { _file = value; }
        }

        public long Offset
        {
            get { return _offset; }
            set { _offset = value; }
        }

        public int Count
        {
            get { return _count; }
            set { _count = value; }
        }
    }
    // End of COMMIT3args.cs
}