/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSClient.RPC.XDR;

namespace NFSClient.Protocols.V3.RPC
{
    public class ExtendedReadFolderArguments : IXdrData
    {
        private NFSHandle _dir;
        private NFSCookie _cookie;
        private byte[] _cookieverf;
        private int _dircount;
        private int _maxcount;

        public ExtendedReadFolderArguments()
        { }

        public ExtendedReadFolderArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            _dir.XdrEncode(xdr);
            _cookie.XdrEncode(xdr);
            xdr.XdrEncodeOpaque(_cookieverf, NFSv3Protocol.NFS3_COOKIEVERFSIZE);
            xdr.XdrEncodeInt(_dircount);
            xdr.XdrEncodeInt(_maxcount);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            _dir = new NFSHandle();
            _dir.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            _dir.XdrDecode(xdr);
            _cookie = new NFSCookie(xdr);
            _cookieverf = xdr.XdrDecodeOpaque(NFSv3Protocol.NFS3_COOKIEVERFSIZE);
            _dircount = xdr.XdrDecodeInt();
            _maxcount = xdr.XdrDecodeInt();
        }

        public NFSHandle Directory
        {
            get
            { return this._dir; }
            set
            { this._dir = value; }
        }

        public NFSCookie Cookie
        {
            get
            { return this._cookie; }
            set
            { this._cookie = value; }
        }

        public byte[] CookieVerification
        {
            get
            { return this._cookieverf; }
            set
            { this._cookieverf = value; }
        }

        public int DirectoryLength
        {
            get
            { return this._dircount; }
            set
            { this._dircount = value; }
        }

        public int MaximumLength
        {
            get
            { return this._maxcount; }
            set
            { this._maxcount = value; }
        }
    }
    // End of READDIRPLUS3args.cs
}