/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSClient.Protocols.Commons;
using NFSClient.RPC.XDR;

namespace NFSClient.Protocols.V3.RPC
{
    public class ExtendedReadFolderAccessOK : IXdrData
    {
        private PostOperationAttributes _dir_attributes;
        private byte[] _cookieverf;
        private FolderList _reply;

        public ExtendedReadFolderAccessOK()
        { }

        public ExtendedReadFolderAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._dir_attributes.XdrEncode(xdr);
            xdr.XdrEncodeOpaque(this._cookieverf, NFSv3Protocol.NFS3_COOKIEVERFSIZE);
            this._reply.XdrEncode(xdr);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._dir_attributes = new PostOperationAttributes(xdr);
            this._cookieverf = xdr.XdrDecodeOpaque(NFSv3Protocol.NFS3_COOKIEVERFSIZE);
            this._reply = new FolderList(xdr);
        }

        public PostOperationAttributes Attributes
        {
            get
            { return this._dir_attributes; }
        }

        public byte[] CookieVerification
        {
            get
            { return this._cookieverf; }
        }

        public FolderList Reply
        {
            get
            { return this._reply; }
        }
    }

    public class ExtendedReadFolderAccessFAIL : IXdrData
    {
        private PostOperationAttributes _dir_attributes;

        public ExtendedReadFolderAccessFAIL()
        { }

        public ExtendedReadFolderAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        { this._dir_attributes.XdrEncode(xdr); }

        public void XdrDecode(XdrDecodingStream xdr)
        { this._dir_attributes = new PostOperationAttributes(xdr); }

        public PostOperationAttributes Attributes
        {
            get
            { return this._dir_attributes; }
        }
    }

    public class FolderList : IXdrData
    {
        private FolderEntry _entries;
        private bool _eof;

        public FolderList()
        { }

        public FolderList(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            if (this._entries != null)
            {
                xdr.XdrEncodeBoolean(true);
                this._entries.XdrEncode(xdr);
            }
            else { xdr.XdrEncodeBoolean(false); }

            xdr.XdrEncodeBoolean(this._eof);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._entries = xdr.XdrDecodeBoolean() ? new FolderEntry(xdr) : null;
            this._eof = xdr.XdrDecodeBoolean();
        }

        public FolderEntry Entries
        {
            get
            { return this._entries; }
        }

        public bool EOF
        {
            get
            { return this._eof; }
        }
    }

    public class FolderEntry : IXdrData
    {
        private long _fileid;
        private Name _name;
        private NFSCookie _cookie;
        private PostOperationAttributes _name_attributes;
        private NFSHandle _name_handle;
        private FolderEntry _nextentry;

        public FolderEntry()
        { }

        public FolderEntry(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            FolderEntry _this = this;

            do
            {
                xdr.XdrEncodeLong(_this._fileid);
                _this._name.XdrEncode(xdr);
                _this._cookie.XdrEncode(xdr);
                _this._name_attributes.XdrEncode(xdr);
                _this._name_handle.XdrEncode(xdr);
                _this = _this._nextentry;
                xdr.XdrEncodeBoolean(_this != null);
            } while (_this != null);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            FolderEntry _this = this;
            FolderEntry _next;

            do
            {
                _this._fileid = xdr.xdrDecodeLong();
                _this._name = new Name(xdr);
                _this._cookie = new NFSCookie(xdr);
                _this._name_attributes = new PostOperationAttributes(xdr);
                _this._name_handle = (xdr.xdrDecodeBoolean() ? new NFSHandle(xdr, 3) : null);
                _next = xdr.xdrDecodeBoolean() ? new FolderEntry() : null;
                _this._nextentry = _next;
                _this = _next;
            } while (_this != null);
        }

        public long FileID
        {
            get
            { return this._fileid; }
        }

        public Name Name
        {
            get
            { return this._name; }
        }

        public NFSCookie Cookie
        {
            get
            { return this._cookie; }
        }

        public PostOperationAttributes Attributes
        {
            get
            { return this._name_attributes; }
        }

        public NFSHandle Handle
        {
            get
            { return this._name_handle; }
        }

        public FolderEntry NextEntry
        {
            get
            { return this._nextentry; }
        }
    }
    // End of READDIRPLUS3res.cs
}