/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSLibrary.RPC.XDR;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class FSInfoAccessOK : IXdrData
    {
        private PostOperationAttributes _obj_attributes;
        private int _rtmax;
        private int _rtpref;
        private int _rtmult;
        private int _wtmax;
        private int _wtpref;
        private int _wtmult;
        private int _dtpref;
        private long _maxfilesize;
        private NFSTimeValue _time_delta;
        private int _properties;

        public FSInfoAccessOK()
        { }

        public FSInfoAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            _obj_attributes.XdrEncode(xdr);
            xdr.XdrEncodeInt(_rtmax);
            xdr.XdrEncodeInt(_rtpref);
            xdr.XdrEncodeInt(_rtmult);
            xdr.XdrEncodeInt(_wtmax);
            xdr.XdrEncodeInt(_wtpref);
            xdr.XdrEncodeInt(_wtmult);
            xdr.XdrEncodeInt(_dtpref);
            xdr.XdrEncodeLong(_maxfilesize);
            _time_delta.XdrEncode(xdr);
            xdr.XdrEncodeInt(_properties);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            _obj_attributes = new PostOperationAttributes(xdr);
            _rtmax = xdr.XdrDecodeInt();
            _rtpref = xdr.XdrDecodeInt();
            _rtmult = xdr.XdrDecodeInt();
            _wtmax = xdr.XdrDecodeInt();
            _wtpref = xdr.XdrDecodeInt();
            _wtmult = xdr.XdrDecodeInt();
            _dtpref = xdr.XdrDecodeInt();
            _maxfilesize = xdr.XdrDecodeLong();
            _time_delta = new NFSTimeValue(xdr);
            _properties = xdr.XdrDecodeInt();
        }

        public int MaximumReadRequestSize
        {
            get
            { return this._rtmax; }
        }

        public int PreferredReadRequestSize
        {
            get
            { return this._rtpref; }
        }

        public int ReadRequestSizeMultiplier
        {
            get
            { return this._rtmult; }
        }

        public int MaximumWriteRequestSize
        {
            get
            { return this._wtmax; }
        }

        public int PreferredWriteRequestSize
        {
            get
            { return this._wtpref; }
        }

        public int WriteRequestSizeMultiplier
        {
            get
            { return this._wtmult; }
        }

        public int PreferredReadFolderRequestSize
        {
            get
            { return this._dtpref; }
        }

        public long MaximumFileSize
        {
            get
            { return this._maxfilesize; }
        }

        public NFSTimeValue DeltaTime
        {
            get
            { return this._time_delta; }
        }

        public PostOperationAttributes Attributes
        {
            get
            { return this._obj_attributes; }
        }

        public int Properties
        {
            get
            { return this._properties; }
        }
    }

    public class FSInfoAccessFAIL : IXdrData
    {
        private PostOperationAttributes obj_attributes;

        public FSInfoAccessFAIL()
        { }

        public FSInfoAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        { this.obj_attributes.XdrEncode(xdr); }

        public void XdrDecode(XdrDecodingStream xdr)
        { this.obj_attributes = new PostOperationAttributes(xdr); }

        public PostOperationAttributes Attributes
        {
            get
            { return this.obj_attributes; }
        }
    }
    // End of FSINFO3res.cs
}