/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSClient.Protocols.Commons;
using NFSClient.RPC.XDR;

namespace NFSClient.Protocols.V3.RPC
{
    public class FSStatisticsAccessOK : IXdrData
    {
        private PostOperationAttributes _obj_attributes;
        private long _tbytes;
        private long _fbytes;
        private long _abytes;
        private long _tfiles;
        private long _ffiles;
        private long _afiles;
        private int _invarsec;

        public FSStatisticsAccessOK()
        { }

        public FSStatisticsAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._obj_attributes.XdrEncode(xdr);
            xdr.XdrEncodeLong(this._tbytes);
            xdr.XdrEncodeLong(this._fbytes);
            xdr.XdrEncodeLong(this._abytes);
            xdr.XdrEncodeLong(this._tfiles);
            xdr.XdrEncodeLong(this._ffiles);
            xdr.XdrEncodeLong(this._afiles);
            xdr.XdrEncodeInt(this._invarsec);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._obj_attributes = new PostOperationAttributes(xdr);
            this._tbytes = xdr.XdrDecodeLong();
            this._fbytes = xdr.XdrDecodeLong();
            this._abytes = xdr.XdrDecodeLong();
            this._tfiles = xdr.XdrDecodeLong();
            this._ffiles = xdr.XdrDecodeLong();
            this._afiles = xdr.XdrDecodeLong();
            this._invarsec = xdr.XdrDecodeInt();
        }

        public long TotalSize
        {
            get
            { return this._tbytes; }
        }

        public long FreeSpace
        {
            get
            { return this._fbytes; }
        }

        public long AuthFreeSpace
        {
            get
            { return this._abytes; }
        }

        public long TotalFileSlot
        {
            get
            { return this._tfiles; }
        }

        public long FreeFileSlot
        {
            get
            { return this._ffiles; }
        }

        public long AuthFreeSlot
        {
            get
            { return this._afiles; }
        }

        public int VolatileSecond
        {
            get
            { return this._invarsec; }
        }

        public PostOperationAttributes Attributes
        {
            get
            { return this._obj_attributes; }
        }
    }

    public class FSStatisticsAccessFAIL : IXdrData
    {
        private PostOperationAttributes obj_attributes;

        public FSStatisticsAccessFAIL()
        { }

        public FSStatisticsAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        { this.obj_attributes.XdrEncode(xdr); }

        public void XdrDecode(XdrDecodingStream xdr)
        { this.obj_attributes = new PostOperationAttributes(xdr); }

        public PostOperationAttributes Attributes
        {
            get
            { return this.obj_attributes; }
        }
    }
    // End of FSSTAT3res.cs
}