/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.RPC.XDR;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class MakeFolderArguments : IXdrData
    {
        private ItemOperationArguments _where;
        private MakeAttributes _attributes;

        public MakeFolderArguments()
        { }

        public MakeFolderArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._where.XdrEncode(xdr);
            this._attributes.XdrEncode(xdr);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._where = new ItemOperationArguments(xdr);
            this._attributes = new MakeAttributes(xdr);
        }

        public ItemOperationArguments Where
        {
            get
            { return this._where; }
            set
            { this._where = value; }
        }

        public MakeAttributes Attributes
        {
            get
            { return this._attributes; }
            set
            { this._attributes = value; }
        }
    }
    // End of MKDIR3args.cs
}
