/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSLibrary.RPC.XDR;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class MakeNodeAccessOK : IXdrData
    {
        private NFSHandle _obj;
        private PostOperationAttributes _obj_attributes;
        private WritingData _dir_wcc;

        public MakeNodeAccessOK()
        { }

        public MakeNodeAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            _obj.XdrEncode(xdr);
            _obj_attributes.XdrEncode(xdr);
            _dir_wcc.XdrEncode(xdr);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            _obj = new NFSHandle();
            _obj.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            _obj.XdrDecode(xdr);
            _obj_attributes = new PostOperationAttributes(xdr);
            _dir_wcc = new WritingData(xdr);
        }

        public NFSHandle Handle
        {
            get { return _obj; }
        }

        public PostOperationAttributes Attributes
        {
            get { return _obj_attributes; }
        }

        public WritingData Data
        {
            get { return _dir_wcc; }
        }
    }

    public class MakeNodeAccessFAIL : IXdrData
    {
        private WritingData _dir_wcc;

        public MakeNodeAccessFAIL()
        { }

        public MakeNodeAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        { _dir_wcc.XdrEncode(xdr); }

        public void XdrDecode(XdrDecodingStream xdr)
        { _dir_wcc = new WritingData(xdr); }

        public WritingData Data
        {
            get { return _dir_wcc; }
        }
    }
    // End of MKNOD3res.cs
}