/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSClient.Protocols.Commons;
using NFSClient.RPC.XDR;

namespace NFSClient.Protocols.V3.RPC
{
    public class PathConfigurationAccessOK : IXdrData
    {
        private PostOperationAttributes _obj_attributes;
        private int _linkmax;
        private int _name_max;
        private bool _no_trunc;
        private bool _chown_restricted;
        private bool _case_insensitive;
        private bool _case_preserving;

        public PathConfigurationAccessOK()
        { }

        public PathConfigurationAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._obj_attributes.XdrEncode(xdr);
            xdr.XdrEncodeInt(this._linkmax);
            xdr.XdrEncodeInt(this._name_max);
            xdr.XdrEncodeBoolean(this._no_trunc);
            xdr.XdrEncodeBoolean(this._chown_restricted);
            xdr.XdrEncodeBoolean(this._case_insensitive);
            xdr.XdrEncodeBoolean(this._case_preserving);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._obj_attributes = new PostOperationAttributes(xdr);
            this._linkmax = xdr.XdrDecodeInt();
            this._name_max = xdr.XdrDecodeInt();
            this._no_trunc = xdr.XdrDecodeBoolean();
            this._chown_restricted = xdr.XdrDecodeBoolean();
            this._case_insensitive = xdr.XdrDecodeBoolean();
            this._case_preserving = xdr.XdrDecodeBoolean();
        }

        public PostOperationAttributes Attributes
        {
            get
            { return this._obj_attributes; }
        }

        public int MaximumHardLinks
        {
            get
            { return this._linkmax; }
        }

        public int MaximumNameLength
        {
            get
            { return this._name_max; }
        }

        public bool NoTrunticate
        {
            get
            { return this._no_trunc; }
        }

        public bool CHOWNRestricted
        {
            get
            { return this._chown_restricted; }
        }

        public bool CaseInsensitive
        {
            get
            { return this._case_insensitive; }
        }

        public bool CasePreserving
        {
            get
            { return this._case_preserving; }
        }
    }

    public class PathConfigurationAccessFAIL : IXdrData
    {
        private PostOperationAttributes _obj_attributes;

        public PathConfigurationAccessFAIL()
        { }

        public PathConfigurationAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        { this._obj_attributes.XdrEncode(xdr); }

        public void XdrDecode(XdrDecodingStream xdr)
        { this._obj_attributes = new PostOperationAttributes(xdr); }

        public PostOperationAttributes Attributes
        {
            get
            { return this._obj_attributes; }
        }
    }
    // End of PATHCONF3res.cs
}