/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSLibrary.RPC.XDR;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class ReadAccessOK : IXdrData
    {
        private PostOperationAttributes _attributes;
        private int _count;
        private bool _eof;
        private byte[] _data;

        public ReadAccessOK()
        { }

        public ReadAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._attributes.XdrEncode(xdr);
            xdr.XdrEncodeInt(this._count);
            xdr.XdrEncodeBoolean(this._eof);
            xdr.XdrEncodeDynamicOpaque(this._data);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._attributes = new PostOperationAttributes(xdr);
            this._count = xdr.XdrDecodeInt();
            this._eof = xdr.XdrDecodeBoolean();
            this._data = xdr.XdrDecodeDynamicOpaque();
        }

        public PostOperationAttributes Attributes
        {
            get
            { return this._attributes; }
        }

        public int Count
        {
            get
            { return this._count; }
        }

        public bool EOF
        {
            get
            { return this._eof; }
        }

        public byte[] Data
        {
            get
            { return this._data; }
        }
    }

    public class ReadAccessFAIL : IXdrData
    {
        private PostOperationAttributes _attributes;

        public ReadAccessFAIL()
        { }

        public ReadAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        { this._attributes.XdrEncode(xdr); }

        public void XdrDecode(XdrDecodingStream xdr)
        { this._attributes = new PostOperationAttributes(xdr); }

        public PostOperationAttributes Attributes
        {
            get
            { return this._attributes; }
        }
    }
    // End of readres.cs
}