/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSClient.Protocols.Commons;
using NFSClient.RPC.XDR;

namespace NFSClient.Protocols.V3.RPC
{
    public class ReadFolderAccessResultOK : IXdrData
    {
        private PostOperationAttributes _dir_attributes;
        private byte[] _cookieverf;
        private ItemAccessOK _reply;

        public ReadFolderAccessResultOK()
        { }

        public ReadFolderAccessResultOK(XdrDecodingStream xdr)
        { }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            // Implementation will be added here
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            // Implementation will be added here
        }
    }

    public class ItemAccessOK : IXdrData
    {
        private Entry _entries;
        private bool _eof;

        public ItemAccessOK()
        { }

        public ItemAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            if (this._entries != null)
            {
                xdr.XdrEncodeBoolean(true);
                this._entries.XdrEncode(xdr);
            }
            else { xdr.XdrEncodeBoolean(false); };

            xdr.XdrEncodeBoolean(this._eof);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._entries = xdr.XdrDecodeBoolean() ? new Entry(xdr) : null;
            this._eof = xdr.XdrDecodeBoolean();
        }

        public Entry Entries
        {
            get
            { return this._entries; }
        }

        public bool EOF
        {
            get
            { return this._eof; }
        }
    }

    public class ReadFolderAccessResultFAIL : IXdrData
    {
        private PostOperationAttributes _dir_attributes;

        public ReadFolderAccessResultFAIL()
        { }

        public ReadFolderAccessResultFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        { this._dir_attributes.XdrEncode(xdr); }

        public void XdrDecode(XdrDecodingStream xdr)
        { this._dir_attributes = new PostOperationAttributes(xdr); }

        public PostOperationAttributes Attributes
        {
            get
            { return this._dir_attributes; }
        }
    }
    // End of READDIR3res.cs
}