/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSLibrary.RPC.XDR;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class ReadFolderArguments : IXdrData
    {
        private NFSHandle _item;
        private NFSCookie _cookie;
        private byte[] _cookieverf;
        private int _count;

        public ReadFolderArguments()
        { }

        public ReadFolderArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._item.XdrEncode(xdr);
            this._cookie.XdrEncode(xdr);

            xdr.XdrEncodeOpaque(this._cookieverf, NFSv3Protocol.NFS3_COOKIEVERFSIZE);
            xdr.XdrEncodeInt(this._count);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._item = new NFSHandle();
            this._item.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            this._item.XdrDecode(xdr);
            this._cookie = new NFSCookie(xdr);
            this._cookieverf = xdr.XdrDecodeOpaque(NFSv3Protocol.NFS3_COOKIEVERFSIZE);
            this._count = xdr.XdrDecodeInt();
        }

        public NFSHandle HandleObject
        {
            get
            { return this._item; }
            set
            { this._item = value; }
        }

        public NFSCookie Cookie
        {
            get
            { return this._cookie; }
            set
            { this._cookie = value; }
        }

        public byte[] CookieData
        {
            get
            { return this._cookieverf; }
            set
            { this._cookieverf = value; }
        }

        public int Count
        {
            get
            { return this._count; }
            set
            { this._count = value; }
        }
    }
    // End of READDIR3args.cs
}