/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSClient.RPC.XDR;

namespace NFSClient.Protocols.V3.RPC
{
    public class SetAttributeArguments : IXdrData
    {
        private NFSHandle _obj;
        private MakeAttributes _new_attributes;
        private bool _guardcheck;
        private NFSTimeValue _guardctime;

        public SetAttributeArguments()
        { }

        public SetAttributeArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            _obj.XdrEncode(xdr);
            _new_attributes.XdrEncode(xdr);
            xdr.XdrEncodeBoolean(_guardcheck);
            if (_guardcheck)
            { _guardctime.XdrEncode(xdr); }
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            _obj = new NFSHandle();
            _obj.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            _obj.XdrDecode(xdr);
            _new_attributes = new MakeAttributes(xdr);
            _guardcheck = xdr.XdrDecodeBoolean();
            if (_guardcheck)
            { _guardctime = new NFSTimeValue(xdr); }
        }

        public NFSHandle Handle
        {
            get
            { return this._obj; }
            set
            { this._obj = value; }
        }

        public MakeAttributes Attributes
        {
            get
            { return this._new_attributes; }
            set
            { this._new_attributes = value; }
        }

        public bool GuardCheck
        {
            get
            { return this._guardcheck; }
            set
            { this._guardcheck = value; }
        }

        public NFSTimeValue GuardCreateTime
        {
            get
            { return this._guardctime; }
            set
            { this._guardctime = value; }
        }
    }
    // End of SETATTR3args.cs
}