/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSLibrary.RPC.XDR;

namespace NFSLibrary.Protocols.V3.RPC
{
    public class WriteArguments : XdrAble
    {
        private NFSHandle _file;
        private long _offset;
        private int _count;
        private StableHow _stable;
        private byte[] _data;

        public WriteArguments()
        { }

        public WriteArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._file.XdrEncode(xdr);
            xdr.XdrEncodeLong(this._offset);
            xdr.XdrEncodeInt(this._count);
            xdr.XdrEncodeInt((int)this._stable);
            xdr.XdrEncodeDynamicOpaque(this._data);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._file = new NFSHandle();
            this._file.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            this._file.XdrDecode(xdr);
            this._offset = xdr.XdrDecodeLong();
            this._count = xdr.XdrDecodeInt();
            this._stable = (StableHow)xdr.XdrDecodeInt();
            this._data = xdr.XdrDecodeDynamicOpaque();
        }

        public NFSHandle File
        {
            get
            { return this._file; }
            set
            { this._file = value; }
        }

        public long Offset
        {
            get
            { return this._offset; }
            set
            { this._offset = value; }
        }

        public int Count
        {
            get
            { return this._count; }
            set
            { this._count = value; }
        }

        public StableHow Stable
        {
            get
            { return this._stable; }
            set
            { this._stable = value; }
        }       

        public byte[] Data
        {
            get
            { return this._data; }
            set
            { this._data = value; }
        }
    }
    // End of writeargs.cs
}