/*
 * Automatically generated by jrpcgen 1.0.7 on 29.11.2012
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using NFSLibrary.Protocols.Commons;
using NFSLibrary.RPC.XDR;

namespace NFSLibrary.Protocols.V3.RPC
{
    public enum StableHow
    {
        UNSTABLE = 0,
        DATA_SYNC = 1,
        FILE_SYNC = 2
    }

    public class WriteAccessOK : XdrAble
    {
        private WritingData _file_wcc;
        private int _count;
        private StableHow _committed;
        private byte[] _verf;

        public WriteAccessOK()
        { }

        public WriteAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._file_wcc.XdrEncode(xdr);
            xdr.XdrEncodeInt(this._count);
            xdr.XdrEncodeInt((int)this._committed);
            xdr.XdrEncodeOpaque(this._verf, NFSv3Protocol.NFS3_WRITEVERFSIZE);
        }

        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._file_wcc = new WritingData(xdr);
            this._count = xdr.XdrDecodeInt();
            this._committed = (StableHow)xdr.XdrDecodeInt();
            this._verf = xdr.XdrDecodeOpaque(NFSv3Protocol.NFS3_WRITEVERFSIZE);
        }

        public WritingData Data
        {
            get
            { return this._file_wcc; }
        }

        public int Count
        {
            get
            { return this._count; }
        }

        public StableHow Committed
        {
            get
            { return this._committed; }
        }

        public byte[] Verification
        {
            get
            { return this._verf; }
        }
    }

    public class WriteAccessFAIL : XdrAble
    {
        private WritingData _dir_wcc;

        public WriteAccessFAIL()
        { }

        public WriteAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        public void XdrEncode(XdrEncodingStream xdr)
        { this._dir_wcc.XdrEncode(xdr); }

        public void XdrDecode(XdrDecodingStream xdr)
        { this._dir_wcc = new WritingData(xdr); }

        public WritingData Data
        {
            get
            { return this._dir_wcc; }
        }
    }
    // End of WRITE3res.cs
}